name: Holdem

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  js-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      - name: Yarn install
        run: yarn install
        working-directory: ./server
      - name: Run Tests
        working-directory: ./server
        run: yarn jest
